# Generated by Django 4.2.16 on 2024-10-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveSmallIntegerField(max_length=2, verbose_name='Возраст')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('tel', models.CharField(max_length=255, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Гитары',
                'db_table': 'users_app_users',
            },
        ),
    ]
