version: "3.8"
services:
  pg:
    image: "postgres:14"
    restart: "no"
    container_name: inspectr_db
    env_file:
      - .env
    ports:
      - "5432:5432"

  back:
    build: .
    container_name: inspectr_back
    restart: "no"
    env_file:
      - .env
    ports:
      - "8003:8003"
    volumes:
      - ./src:/inspectr_test
    depends_on:
      - pg
    command: /start